services:
  - type: web
    name: socket-server
    env: node
    buildCommand: npm install
    startCommand: node socket-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://lit-card-game.vercel.app
    healthCheckPath: /health
    autoDeploy: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://lit-card-game.vercel.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, OPTIONS, PUT, DELETE
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization, X-Requested-With, Accept, Origin
      - path: /*
        name: Access-Control-Allow-Credentials
        value: true
      - path: /*
        name: Access-Control-Max-Age
        value: 86400
      - path: /*
        name: Vary
        value: Origin
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: 0 