services:
  - type: web
    name: lit-card-game-socket
    env: node
    rootDir: socket-server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://lit-card-game.vercel.app
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 